title: Luis Ramos # your name (or website title) here
logo: "/images/Screen Shot 2020-03-09 at 13.13.02.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A great education makes anything possible. Fortunate for my deep problem solving skills from pursuing Mechanical Engineering. Now, my passion is in growing my understanding in the field of Computer Engineering. Involved in University projects from the development of a workout/gym site à la Uber/Tinder, to a design project building an elderly focused smart assistant in the form of a puppy, to tackle loneliness.   
  <br><br>
  My internship at Skyline Communications, with their DataMiner program, and courses sharpening coding, networking & hardware building skills has lead me to my current endeavor: developing a varied take on the classic Snake Game using an Arduino, Keypad & LCD while developing an app serving as user's profile on allergen and lactose information for restaurants.  
  <br><br>
  <a href="https://www.linkedin.com/in/luisgramosg/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
