title: Luis Ramos # your name (or website title) here
logo: "/images/Screen Shot 2020-03-09 at 13.13.02.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  TEST 1 
  <br><br>
  Test 2 
  <br><br>
  <a href="https://www.linkedin.com/in/luisgramosg/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
